spring:
  datasource: # spring数据源的相关配置
    dynamic:
      primary: alarm
      strict: false
      datasource:
        alarm:
          url: jdbc:postgresql://127.0.0.1:5432/alarm?useUnicode=true&characterEncoding=utf8&currentSchema=public&useAffectedRows=true&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
          driver-classname: org.postgresql.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 10
      connection-test-query: "SELECT 1"
      pool-name: "mainPool"
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
      auto-commit: true
  redis:
    host: 127.0.0.1       #Redis服务器连接端口
    port: 6379     #Redis服务器连接端口
    password:       #Redis服务器连接密码（默认为空）
    pool:
      max-active: 200   #连接池最大连接数（使用负值表示没有限制）
      max-wait: -1     #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10     #连接池中的最大空闲连接
      min-idle: 0     #连接池中的最小空闲连接
    timeout: 10000    #连接超时时间（毫秒）

panda:
  hostname: 127.0.0.1
  port: 8989
  heartbeat-period: 5
  retry-connect-interval: 5 # 当客户端连接服务端失败时，每隔一定的时间进行重连，单位s